//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enclase.Modulos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPrueba4Entities : DbContext
    {
        public BDPrueba4Entities()
            : base("name=BDPrueba4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBBiblioteca> TBBiblioteca { get; set; }
        public virtual DbSet<TBCitas> TBCitas { get; set; }
        public virtual DbSet<TBDoctor> TBDoctor { get; set; }
        public virtual DbSet<TBPaciente> TBPaciente { get; set; }
        public virtual DbSet<TBUsuario> TBUsuario { get; set; }
    }
}
