//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enclase.Modulos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBBiblioteca
    {
        public int IdLibro { get; set; }
        public string nombre { get; set; }
        public Nullable<int> año { get; set; }
        public string especialidad { get; set; }
        public string autor { get; set; }
    }
}
