//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enclase.Modulos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCitas
    {
        public int IdCita { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string previsión { get; set; }
        public string modoCita { get; set; }
        public Nullable<int> idDoctor { get; set; }
        public Nullable<int> idPaciente { get; set; }
    
        public virtual TBDoctor TBDoctor { get; set; }
        public virtual TBPaciente TBPaciente { get; set; }
    }
}
