//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enclase.Modulos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPaciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBPaciente()
        {
            this.TBCitas = new HashSet<TBCitas>();
        }
    
        public int idPaciente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string fono { get; set; }
        public string correo { get; set; }
        public Nullable<int> edad { get; set; }
        public string dirección { get; set; }
        public string previsión { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCitas> TBCitas { get; set; }
    }
}
