//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enclase.Modulos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUsuario
    {
        public int IdUsuario { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public string correo { get; set; }
        public string fono { get; set; }
        public string perfil { get; set; }
    }
}
